# This file contains the ascii images for starting the game
Class Images
    def self.title
                                                                      
                                                                                                                                                                                                                                                                                                  
puts "  LLLLLLLLLLL               iiii          tttt               tttt          lllllll                          RRRRRRRRRRRRRRRRR                                             iiii                                                           AAA                                                      
        L:::::::::L              i::::i      ttt:::t            ttt:::t          l:::::l                          R::::::::::::::::R                                           i::::i                                                         A:::A                                                     
        L:::::::::L               iiii       t:::::t            t:::::t          l:::::l                          R::::::RRRRRR:::::R                                           iiii                                                         A:::::A                                                    
        LL:::::::LL                          t:::::t            t:::::t          l:::::l                          RR:::::R     R:::::R                                                                                                      A:::::::A                                                   
        L:::::L               iiiiiiittttttt:::::tttttttttttttt:::::ttttttt     l::::l     eeeeeeeeeeee           R::::R     R:::::R    eeeeeeeeeeee        cccccccccccccccciiiiiiippppp   ppppppppp       eeeeeeeeeeee                    A:::::::::A          ppppp   ppppppppp   ppppp   ppppppppp     ".colorize(:cyan)   
puts "  L:::::L               i:::::it:::::::::::::::::tt:::::::::::::::::t     l::::l   ee::::::::::::ee         R::::R     R:::::R  ee::::::::::::ee    cc:::::::::::::::ci:::::ip::::ppp:::::::::p    ee::::::::::::ee                 A:::::A:::::A         p::::ppp:::::::::p  p::::ppp:::::::::p  
        L:::::L                i::::it:::::::::::::::::tt:::::::::::::::::t     l::::l  e::::::eeeee:::::ee       R::::RRRRRR:::::R  e::::::eeeee:::::ee c:::::::::::::::::c i::::ip:::::::::::::::::p  e::::::eeeee:::::ee              A:::::A A:::::A        p:::::::::::::::::p p:::::::::::::::::p 
        L:::::L                i::::itttttt:::::::tttttttttttt:::::::tttttt     l::::l e::::::e     e:::::e       R:::::::::::::RR  e::::::e     e:::::ec:::::::cccccc:::::c i::::ipp::::::ppppp::::::pe::::::e     e:::::e             A:::::A   A:::::A       pp::::::ppppp::::::ppp::::::ppppp::::::p ".colorize(:light_magneta)
        L:::::L                i::::i      t:::::t            t:::::t           l::::l e:::::::eeeee::::::e       R::::RRRRRR:::::R e:::::::eeeee::::::ec::::::c     ccccccc i::::i p:::::p     p:::::pe:::::::eeeee::::::e            A:::::A     A:::::A       p:::::p     p:::::p p:::::p     p:::::p
        L:::::L                i::::i      t:::::t            t:::::t           l::::l e:::::::::::::::::e        R::::R     R:::::Re:::::::::::::::::e c:::::c              i::::i p:::::p     p:::::pe:::::::::::::::::e            A:::::AAAAAAAAA:::::A      p:::::p     p:::::p p:::::p     p:::::p
        L:::::L                i::::i      t:::::t            t:::::t           l::::l e::::::eeeeeeeeeee         R::::R     R:::::Re::::::eeeeeeeeeee  c:::::c              i::::i p:::::p     p:::::pe::::::eeeeeeeeeee            A:::::::::::::::::::::A     p:::::p     p:::::p p:::::p     p:::::p
        L:::::L         LLLLLL i::::i      t:::::t    tttttt  t:::::t    tttttt l::::l e:::::::e                  R::::R     R:::::Re:::::::e           c::::::c     ccccccc i::::i p:::::p    p::::::pe:::::::e                    A:::::AAAAAAAAAAAAA:::::A    p:::::p    p::::::p p:::::p    p::::::p
        LL:::::::LLLLLLLLL:::::Li::::::i     t::::::tttt:::::t  t::::::tttt:::::tl::::::le::::::::e               RR:::::R     R:::::Re::::::::e          c:::::::cccccc:::::ci::::::ip:::::ppppp:::::::pe::::::::e                  A:::::A             A:::::A   p:::::ppppp:::::::p p:::::ppppp:::::::p
        L::::::::::::::::::::::Li::::::i     tt::::::::::::::t  tt::::::::::::::tl::::::l e::::::::eeeeeeee       R::::::R     R:::::R e::::::::eeeeeeee   c:::::::::::::::::ci::::::ip::::::::::::::::p  e::::::::eeeeeeee         A:::::A               A:::::A  p::::::::::::::::p  p::::::::::::::::p 
        L::::::::::::::::::::::Li::::::i       tt:::::::::::tt    tt:::::::::::ttl::::::l  ee:::::::::::::e       R::::::R     R:::::R  ee:::::::::::::e    cc:::::::::::::::ci::::::ip::::::::::::::pp    ee:::::::::::::e        A:::::A                 A:::::A p::::::::::::::pp   p::::::::::::::pp  
        LLLLLLLLLLLLLLLLLLLLLLLLiiiiiiii         ttttttttttt        ttttttttttt  llllllll    eeeeeeeeeeeeee       RRRRRRRR     RRRRRRR    eeeeeeeeeeeeee      cccccccccccccccciiiiiiiip::::::pppppppp        eeeeeeeeeeeeee       AAAAAAA                   AAAAAAAp::::::pppppppp     p::::::pppppppp    
                                                                                                                                                                                    p:::::p                                                                      p:::::p             p:::::p            
                                                                                                                                                                                    p:::::p                                                                      p:::::p             p:::::p            
                                                                                                                                                                                    p:::::::p                                                                    p:::::::p           p:::::::p           
                                                                                                                                                                                    p:::::::p                                                                    p:::::::p           p:::::::p           
                    
    
end